import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import prismaInstance from '../lib/prisma'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Swarm</h1>

        <p className={styles.description}>That&apos;s pretty empty right now</p>
      </main>
    </div>
  )
}

// export async function getStaticProps() {
//   const tickets = await prisma.ticket.findMany({
//     orderBy: { createdAt: 'desc' },
//   })

//   return { props: { tickets } }
// }

export default Home
